# Generated by Django 6.0.3 on 2026-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_hashtag_post_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="post_photo"),
        ),
    ]
